version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - # 把宿主机的 conda 环境挂载到容器内
      - /root/miniconda3/envs/chemistry:/opt/conda
    environment:
      - RDKIT_PYTHON_PATH=/opt/conda/bin/python
    depends_on:
      - backend

volumes:
  pgdata:
